#!/usr/bin/env python3
"""Build bounded, derived synthesis artifacts downstream of automatic overview.md.

This module never writes wiki/overview.md and never calls an LLM. The coding agent
fills structured JSON in the staging directory between plan and render.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

GENERATED_NOTICE = "<!-- Generated by tools.synthesis; do not edit manually. -->"
CURRENT_START = "## Current Synthesis"
CURRENT_END = "## Open Questions"
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")
CLAIM_ID_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
VALID_STATUSES = {"supported", "qualified", "contested", "source-scoped"}
GLOBAL_SUMMARY_MAX_CHARS = 180
CURRENT_FRONTMATTER_KEYS = (
    "schema_version",
    "generated",
    "synthesis_source",
    "last_updated",
    "as_of_overview_commit",
    "summary",
    "episode_count",
    "source_count",
    "paragraph_count",
    "topic_count",
)


class SynthesisError(ValueError):
    """The synthesis source, state, or staged model output is invalid."""


@dataclass(frozen=True)
class Paths:
    root: Path

    @property
    def overview(self) -> Path:
        return self.root / "wiki" / "overview.md"

    @property
    def config(self) -> Path:
        return self.root / "config" / "synthesis-topics.json"

    @property
    def output(self) -> Path:
        return self.root / "wiki" / "_generated" / "synthesis"

    @property
    def stage(self) -> Path:
        return self.root / ".synthesis-staging"

    @property
    def manifest(self) -> Path:
        return self.output / "manifest.json"


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n"


def digest_value(value: Any) -> str:
    payload = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def digest_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def normalize_paragraph(text: str) -> str:
    return " ".join(text.split())


def generated_summary(markdown: str) -> str:
    frontmatter = re.match(
        rf"{re.escape(GENERATED_NOTICE)}\n---\n(?P<body>.*?)\n---\n",
        markdown,
        re.DOTALL,
    )
    if frontmatter is None:
        raise SynthesisError("Generated compact synthesis is missing its summary")
    summary_lines: list[str] = []
    for line in frontmatter.group("body").splitlines():
        raw_key, separator, _value = line.partition(":")
        if not separator:
            continue
        key = raw_key.strip()
        if key.startswith('"') and key.endswith('"'):
            try:
                key = json.loads(key)
            except json.JSONDecodeError:
                continue
        elif key.startswith("'") and key.endswith("'"):
            key = key[1:-1].replace("''", "'")
        if key == "summary":
            summary_lines.append(line)
    if not summary_lines:
        raise SynthesisError("Generated compact synthesis is missing its summary")
    if len(summary_lines) != 1:
        raise SynthesisError("Generated compact synthesis must contain exactly one summary")
    frontmatter_keys: list[str] = []
    for line in frontmatter.group("body").splitlines():
        raw_key, separator, _value = line.partition(":")
        if not separator:
            raise SynthesisError("Generated compact synthesis frontmatter is not canonical")
        frontmatter_keys.append(raw_key)
    if tuple(frontmatter_keys) != CURRENT_FRONTMATTER_KEYS:
        raise SynthesisError("Generated compact synthesis frontmatter is not canonical")
    match = re.fullmatch(r"summary:[ \t]*(.+)", summary_lines[0])
    if match is None:
        raise SynthesisError("Generated compact synthesis has an invalid summary")
    try:
        summary = json.loads(match.group(1))
    except json.JSONDecodeError as error:
        raise SynthesisError("Generated compact synthesis has an invalid summary") from error
    if not isinstance(summary, str) or not summary.strip():
        raise SynthesisError("Generated compact synthesis has an invalid summary")
    return summary.strip()


def extract_wikilinks(text: str) -> list[str]:
    return sorted({match.strip() for match in WIKILINK_RE.findall(text) if match.strip()})


def read_json(path: Path, *, required: bool = True) -> dict[str, Any]:
    if not path.exists():
        if required:
            raise SynthesisError(f"Required JSON file does not exist: {path}")
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise SynthesisError(f"Invalid JSON file {path}: {error}") from error
    if not isinstance(value, dict):
        raise SynthesisError(f"JSON root must be an object: {path}")
    return value


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    os.replace(temporary, path)


def load_config(root: Path) -> dict[str, Any]:
    config = read_json(Paths(root).config)
    topics = config.get("topics")
    if config.get("version") != 1 or not isinstance(topics, list) or not topics:
        raise SynthesisError("synthesis-topics.json must have version 1 and a non-empty topics list")
    ids: list[str] = []
    for topic in topics:
        if not isinstance(topic, dict):
            raise SynthesisError("Each controlled topic must be an object")
        topic_id = topic.get("id")
        if not isinstance(topic_id, str) or not CLAIM_ID_RE.fullmatch(topic_id):
            raise SynthesisError(f"Invalid controlled topic id: {topic_id!r}")
        if not isinstance(topic.get("title"), str) or not topic["title"].strip():
            raise SynthesisError(f"Controlled topic {topic_id} has no title")
        terms = topic.get("terms")
        if not isinstance(terms, list) or any(not isinstance(term, str) for term in terms):
            raise SynthesisError(f"Controlled topic {topic_id} terms must be strings")
        ids.append(topic_id)
    if len(ids) != len(set(ids)) or "cross-domain" not in ids:
        raise SynthesisError("Controlled topic ids must be unique and include cross-domain")
    gate = config.get("global_compaction", {})
    for key in ("max_ingests", "max_age_hours", "max_chars"):
        if not isinstance(gate.get(key), int) or gate[key] <= 0:
            raise SynthesisError(f"global_compaction.{key} must be a positive integer")
    return config


def extract_current_synthesis(overview: str) -> str:
    start_count = sum(1 for line in overview.splitlines() if line.strip() == CURRENT_START)
    end_count = sum(1 for line in overview.splitlines() if line.strip() == CURRENT_END)
    if start_count != 1 or end_count != 1:
        raise SynthesisError("overview.md must contain exactly one Current Synthesis and Open Questions heading")
    before, remainder = overview.split(CURRENT_START, 1)
    current, _questions = remainder.split(CURRENT_END, 1)
    if before.find(CURRENT_END) >= 0 or not current.strip():
        raise SynthesisError("Current Synthesis headings are out of order or the section is empty")
    return current.strip()


def overview_date(overview: str) -> str:
    match = re.search(r"(?m)^last_updated:\s*[\"']?(\d{4}-\d{2}-\d{2})[\"']?\s*$", overview)
    if not match:
        raise SynthesisError("overview.md front matter has no valid last_updated date")
    dt.date.fromisoformat(match.group(1))
    return match.group(1)


def git_head(root: Path) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=root, text=True, capture_output=True, check=False
    )
    return result.stdout.strip() if result.returncode == 0 else "unknown"


def parse_now(value: str | None) -> dt.datetime:
    if value is None:
        return dt.datetime.now(dt.timezone.utc)
    normalized = value.replace("Z", "+00:00")
    parsed = dt.datetime.fromisoformat(normalized)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed.astimezone(dt.timezone.utc)


def topic_map(config: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {topic["id"]: topic for topic in config["topics"]}


def _expand_topic_search_text(text: str) -> str:
    """Add deterministic word forms for CamelCase/slug wikilink targets."""
    expanded = [normalize_paragraph(text)]
    for target in extract_wikilinks(text):
        words = re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", " ", target)
        expanded.append(re.sub(r"[-_]", " ", words))
    return " ".join(expanded).casefold()


def assign_topics(text: str, config: dict[str, Any]) -> tuple[str, list[str], dict[str, int]]:
    searchable = _expand_topic_search_text(text)
    scores: dict[str, int] = {}
    ordered_ids = [topic["id"] for topic in config["topics"]]
    for topic in config["topics"]:
        topic_id = topic["id"]
        if topic_id == "cross-domain":
            continue
        score = 0
        for raw_term in topic["terms"]:
            term = raw_term.strip().casefold()
            if not term:
                continue
            if re.search(rf"(?<!\w){re.escape(term)}(?!\w)", searchable):
                score += 1
        if score:
            scores[topic_id] = score
    if not scores:
        return "cross-domain", [], {}
    primary = max(scores, key=lambda item: (scores[item], -ordered_ids.index(item)))
    primary_score = scores[primary]
    secondary = [
        topic_id
        for topic_id in ordered_ids
        if topic_id != primary
        and scores.get(topic_id, 0) > 0
        and (
            (primary_score == 1 and scores[topic_id] == 1)
            or (scores[topic_id] >= 2 and scores[topic_id] * 2 >= primary_score)
        )
    ][:2]
    return primary, secondary, scores


def corpus_coverage(root: Path) -> dict[str, int]:
    """Return the source-note snapshot represented by the automatic Overview."""
    sources = root / "wiki" / "sources"
    source_count = 0
    episode_ids: set[str] = set()
    if not sources.is_dir():
        return {"episode_count": 0, "source_count": 0}
    for path in sorted(sources.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        if not re.search(r"(?m)^type:\s*[\"']?source[\"']?\s*$", text):
            continue
        source_count += 1
        match = re.search(r"(?m)^source_file:\s*[\"']?(.*?)[\"']?\s*$", text)
        episode_ids.add(match.group(1).strip() if match and match.group(1).strip() else path.stem)
    return {"episode_count": len(episode_ids), "source_count": source_count}


def build_plan(root: Path, *, now: str | None = None, force_global: bool = False) -> dict[str, Any]:
    del now  # The semantic plan is content-addressed; time is used only by the global gate.
    paths = Paths(root)
    config = load_config(root)
    overview = paths.overview.read_text(encoding="utf-8")
    current = extract_current_synthesis(overview)
    paragraphs: list[dict[str, Any]] = []
    seen: set[str] = set()
    for raw in re.split(r"\n\s*\n", current):
        text = raw.strip()
        if not text:
            continue
        normalized = normalize_paragraph(text)
        paragraph_id = digest_text(normalized)
        if paragraph_id in seen:
            raise SynthesisError(f"Duplicate normalized Current Synthesis paragraph: {paragraph_id}")
        seen.add(paragraph_id)
        primary, secondary, scores = assign_topics(text, config)
        paragraphs.append(
            {
                "id": paragraph_id,
                "text": text,
                "wikilinks": sorted(set(WIKILINK_RE.findall(text))),
                "primary_topic": primary,
                "secondary_topics": secondary,
                "topic_scores": scores,
            }
        )
    if not paragraphs:
        raise SynthesisError("Current Synthesis contains no natural paragraphs")

    assigned = [paragraph["id"] for paragraph in paragraphs if paragraph["primary_topic"]]
    if len(assigned) != len(paragraphs) or set(assigned) != seen:
        raise SynthesisError("Paragraph topic coverage is incomplete")

    old_manifest = read_json(paths.manifest, required=False)
    old_topics = old_manifest.get("topics", {}) if isinstance(old_manifest.get("topics", {}), dict) else {}
    topics: dict[str, dict[str, Any]] = {}
    dirty: list[str] = []
    configured = topic_map(config)
    for topic_id, topic in configured.items():
        topic_paragraphs = [
            paragraph
            for paragraph in paragraphs
            if paragraph["primary_topic"] == topic_id or topic_id in paragraph["secondary_topics"]
        ]
        if not topic_paragraphs:
            continue
        input_digest = digest_value([paragraph["id"] for paragraph in topic_paragraphs])
        topics[topic_id] = {
            "topic_id": topic_id,
            "title": topic["title"],
            "input_digest": input_digest,
            "paragraph_ids": [paragraph["id"] for paragraph in topic_paragraphs],
        }
        if old_topics.get(topic_id, {}).get("input_digest") != input_digest:
            dirty.append(topic_id)

    return {
        "schema_version": 1,
        "overview_digest": digest_text(overview),
        "current_synthesis_digest": digest_text(current),
        "overview_commit": git_head(root),
        "content_date": overview_date(overview),
        "corpus": corpus_coverage(root),
        "paragraphs": paragraphs,
        "coverage": {
            "paragraph_count": len(paragraphs),
            "assigned_paragraph_ids": assigned,
        },
        "topics": topics,
        "dirty_topics": sorted(dirty),
        "force_global": force_global,
    }


def plan_repository(root: Path, *, now: str | None = None, force_global: bool = False) -> dict[str, Any]:
    plan = build_plan(root, now=now, force_global=force_global)
    paths = Paths(root)
    if paths.stage.exists():
        shutil.rmtree(paths.stage)
    (paths.stage / "inputs").mkdir(parents=True)
    paragraphs = {paragraph["id"]: paragraph for paragraph in plan["paragraphs"]}
    for topic_id in plan["dirty_topics"]:
        topic = plan["topics"][topic_id]
        bundle = {
            "schema_version": 1,
            "topic_id": topic_id,
            "title": topic["title"],
            "overview_digest": plan["overview_digest"],
            "input_digest": topic["input_digest"],
            "instructions": (
                "Using every paragraph below, revise the topic's current state. Merge repetition, "
                "preserve qualifications and conflicts, and ground every claim in listed wikilinks."
            ),
            "paragraphs": [paragraphs[paragraph_id] for paragraph_id in topic["paragraph_ids"]],
        }
        atomic_write(paths.stage / "inputs" / f"{topic_id}.json", canonical_json(bundle))
    atomic_write(paths.stage / "plan.json", canonical_json(plan))
    return plan


def known_wiki_keys(root: Path) -> set[str]:
    keys: set[str] = set()
    for section in ("concepts", "entities", "sources"):
        directory = root / "wiki" / section
        if directory.is_dir():
            keys.update(path.stem for path in directory.glob("*.md") if not path.name.startswith("_"))
    return keys


def _input_links(plan: dict[str, Any], topic_id: str) -> set[str]:
    paragraph_ids = set(plan["topics"][topic_id]["paragraph_ids"])
    return {
        link
        for paragraph in plan["paragraphs"]
        if paragraph["id"] in paragraph_ids
        for link in paragraph["wikilinks"]
    }


def load_topic_claims(
    root: Path,
    topic_id: str,
    plan: dict[str, Any] | None = None,
    *,
    source: Path | None = None,
) -> dict[str, Any]:
    paths = Paths(root)
    if plan is None:
        plan = read_json(paths.stage / "plan.json")
    staged = paths.stage / "claims" / f"{topic_id}.json"
    tracked = paths.output / "claims" / f"{topic_id}.json"
    if source is not None:
        path = source
    elif topic_id in set(plan.get("dirty_topics", [])):
        if not staged.is_file():
            raise SynthesisError(f"Dirty topic {topic_id} has no staged claims")
        path = staged
    else:
        path = tracked
    payload = read_json(path)
    if payload.get("topic_id") != topic_id:
        raise SynthesisError(f"Topic claims {path} has the wrong topic_id")
    summary = payload.get("summary")
    claims = payload.get("claims")
    if not isinstance(summary, str) or not summary.strip() or not isinstance(claims, list):
        raise SynthesisError(f"Topic claims {topic_id} needs a non-empty summary and claims list")
    allowed_links = _input_links(plan, topic_id)
    claim_ids: set[str] = set()
    for claim in claims:
        if not isinstance(claim, dict):
            raise SynthesisError(f"Topic {topic_id} contains a non-object claim")
        claim_id = claim.get("id")
        if not isinstance(claim_id, str) or not CLAIM_ID_RE.fullmatch(claim_id) or claim_id in claim_ids:
            raise SynthesisError(f"Topic {topic_id} has an invalid or duplicate claim id: {claim_id!r}")
        claim_ids.add(claim_id)
        if claim.get("status") not in VALID_STATUSES:
            raise SynthesisError(f"Topic {topic_id} claim {claim_id} has an invalid status")
        statement = claim.get("statement")
        supports = claim.get("supporting_wikilinks")
        qualifications = claim.get("qualifications")
        if not isinstance(statement, str) or not statement.strip():
            raise SynthesisError(f"Topic {topic_id} claim {claim_id} has no statement")
        if not isinstance(supports, list) or any(not isinstance(link, str) for link in supports):
            raise SynthesisError(f"Topic {topic_id} claim {claim_id} has invalid supporting_wikilinks")
        missing = sorted(set(supports) - allowed_links)
        if missing:
            raise SynthesisError(
                f"Topic {topic_id} claim {claim_id} support is not present in topic input: {missing}"
            )
        if not isinstance(qualifications, list) or any(not isinstance(item, str) for item in qualifications):
            raise SynthesisError(f"Topic {topic_id} claim {claim_id} has invalid qualifications")
        if not isinstance(claim.get("global_candidate"), bool):
            raise SynthesisError(f"Topic {topic_id} claim {claim_id} needs global_candidate boolean")
    return payload


def _all_claims(root: Path, plan: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {topic_id: load_topic_claims(root, topic_id, plan) for topic_id in plan["topics"]}


def candidate_records(claims: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for topic_id in sorted(claims):
        for claim in claims[topic_id]["claims"]:
            if claim["global_candidate"]:
                records.append(
                    {
                        "qualified_id": f"{topic_id}:{claim['id']}",
                        "topic_id": topic_id,
                        **claim,
                    }
                )
    return records


def _hours_since(last_updated: str, now: dt.datetime) -> float:
    if not last_updated:
        return float("inf")
    parsed = dt.datetime.fromisoformat(last_updated.replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return (now - parsed.astimezone(dt.timezone.utc)).total_seconds() / 3600


def prepare_global(root: Path, *, now: str | None = None) -> dict[str, Any]:
    paths = Paths(root)
    plan = read_json(paths.stage / "plan.json")
    current_plan = build_plan(root, now=now, force_global=bool(plan.get("force_global")))
    if current_plan["overview_digest"] != plan.get("overview_digest"):
        raise SynthesisError("overview.md changed after synthesis plan; run plan again")
    claims = _all_claims(root, plan)
    candidates = candidate_records(claims)
    material_digest = digest_value(
        {
            "topic_summaries": {
                topic_id: claims[topic_id]["summary"] for topic_id in sorted(claims)
            },
            "global_candidates": candidates,
        }
    )
    manifest = read_json(paths.manifest, required=False)
    previous_global = manifest.get("global", {}) if isinstance(manifest.get("global", {}), dict) else {}
    changed_overview = manifest.get("overview_digest") != plan["overview_digest"]
    pending_ingests = int(previous_global.get("pending_ingests", 0)) + (1 if changed_overview else 0)
    gate = load_config(root)["global_compaction"]
    reasons: list[str] = []
    if plan.get("force_global"):
        reasons.append("forced")
    if previous_global.get("candidate_digest") != material_digest:
        reasons.append("material-candidate-change")
    if pending_ingests >= gate["max_ingests"]:
        reasons.append("max-ingests")
    if previous_global and _hours_since(str(previous_global.get("compacted_at", "")), parse_now(now)) >= gate["max_age_hours"]:
        reasons.append("max-age")
    global_due = bool(reasons)
    global_plan = {
        "schema_version": 1,
        "global_due": global_due,
        "reasons": reasons,
        "candidate_digest": material_digest,
        "pending_ingests": pending_ingests,
        "overview_digest": plan["overview_digest"],
    }
    if global_due:
        global_input = {
            "schema_version": 1,
            "overview_digest": plan["overview_digest"],
            "instructions": (
                "Select five to eight representative claim IDs and compress every topic summary. "
                f"Write a summary of at most {GLOBAL_SUMMARY_MAX_CHARS} characters. "
                "Do not add Update History, Open Questions, or unsupported claims."
            ),
            "topics": [
                {
                    "topic_id": topic_id,
                    "title": plan["topics"][topic_id]["title"],
                    "summary": claims[topic_id]["summary"],
                    "claims": claims[topic_id]["claims"],
                }
                for topic_id in plan["topics"]
            ],
            "global_candidates": candidates,
        }
        atomic_write(paths.stage / "global-input.json", canonical_json(global_input))
    elif (paths.stage / "global-input.json").exists():
        (paths.stage / "global-input.json").unlink()
    atomic_write(paths.stage / "global-plan.json", canonical_json(global_plan))
    return global_plan


def _validate_global(root: Path, plan: dict[str, Any], global_plan: dict[str, Any]) -> dict[str, Any]:
    paths = Paths(root)
    payload = read_json(paths.stage / "global.json")
    summary = payload.get("summary")
    executive = payload.get("executive_claim_ids")
    domains = payload.get("domain_summaries")
    if not isinstance(summary, str) or not summary.strip():
        raise SynthesisError("global.json needs a non-empty summary")
    if len(summary.strip()) > GLOBAL_SUMMARY_MAX_CHARS:
        raise SynthesisError(
            f"global.json summary exceeds {GLOBAL_SUMMARY_MAX_CHARS} characters"
        )
    if not isinstance(executive, list) or not 1 <= len(executive) <= 8 or any(not isinstance(item, str) for item in executive):
        raise SynthesisError("global.json executive_claim_ids must contain one to eight IDs")
    candidates = read_json(paths.stage / "global-input.json")["global_candidates"]
    allowed = {item["qualified_id"] for item in candidates}
    if len(executive) != len(set(executive)) or set(executive) - allowed:
        raise SynthesisError("global.json contains duplicate or unknown executive claim IDs")
    if not isinstance(domains, dict) or set(domains) != set(plan["topics"]):
        raise SynthesisError("global.json domain_summaries must cover every active controlled topic")
    if any(not isinstance(value, str) or not value.strip() for value in domains.values()):
        raise SynthesisError("global.json domain summaries must be non-empty strings")
    if not global_plan.get("global_due"):
        raise SynthesisError("global.json was provided when global compaction is not due")
    return payload


def render_topic(topic: dict[str, Any], claims: dict[str, Any], date: str, commit: str) -> str:
    lines = [
        GENERATED_NOTICE,
        "---",
        "generated: true",
        f"topic_id: {topic['topic_id']}",
        f"title: {json.dumps(topic['title'], ensure_ascii=False)}",
        f"last_updated: {date}",
        f"as_of_overview_commit: {commit}",
        f"input_digest: {topic['input_digest']}",
        "---",
        "",
        f"# {topic['title']}",
        "",
        "## Current State",
        "",
        claims["summary"].strip(),
        "",
        "## Cross-source Findings",
        "",
    ]
    if not claims["claims"]:
        lines.extend(["No stable cross-source finding has been promoted yet.", ""])
    for claim in claims["claims"]:
        lines.extend([f"### {claim['id'].replace('-', ' ').title()}", "", claim["statement"].strip(), ""])
        supports = ", ".join(f"[[{link}]]" for link in claim["supporting_wikilinks"])
        if supports:
            lines.extend([f"**Evidence:** {supports}", ""])
        if claim["qualifications"]:
            lines.extend(["**Qualifications:**", ""])
            lines.extend(f"- {item}" for item in claim["qualifications"])
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_current(
    plan: dict[str, Any],
    claims: dict[str, dict[str, Any]],
    global_payload: dict[str, Any],
) -> str:
    lookup = {
        f"{topic_id}:{claim['id']}": claim
        for topic_id, topic_claims in claims.items()
        for claim in topic_claims["claims"]
    }
    lines = [
        GENERATED_NOTICE,
        "---",
        "schema_version: 1",
        "generated: true",
        "synthesis_source: compact",
        f"last_updated: {plan['content_date']}",
        f"as_of_overview_commit: {plan['overview_commit']}",
        f"summary: {json.dumps(global_payload['summary'].strip(), ensure_ascii=False)}",
        f"episode_count: {plan['corpus']['episode_count']}",
        f"source_count: {plan['corpus']['source_count']}",
        f"paragraph_count: {plan['coverage']['paragraph_count']}",
        f"topic_count: {len(plan['topics'])}",
        "---",
        "",
        "# Current Synthesis",
        "",
        "## Executive Summary",
        "",
    ]
    for qualified_id in global_payload["executive_claim_ids"]:
        lines.append(f"- {lookup[qualified_id]['statement'].strip()}")
    lines.extend(["", "## Synthesis by Domain", ""])
    for topic_id, topic in plan["topics"].items():
        lines.extend([f"### {topic['title']}", "", global_payload["domain_summaries"][topic_id].strip(), ""])
        candidates = [claim for claim in claims[topic_id]["claims"] if claim["global_candidate"]][:2]
        for claim in candidates:
            supports = ", ".join(f"[[{link}]]" for link in claim["supporting_wikilinks"])
            lines.append(f"- {claim['statement'].strip()}" + (f" Evidence: {supports}." if supports else ""))
        if candidates:
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_repository(root: Path, *, now: str | None = None) -> dict[str, Any]:
    paths = Paths(root)
    plan = read_json(paths.stage / "plan.json")
    current_plan = build_plan(root, now=now, force_global=bool(plan.get("force_global")))
    if current_plan["overview_digest"] != plan.get("overview_digest"):
        raise SynthesisError("overview.md changed after synthesis plan; refusing stale render")
    global_plan = read_json(paths.stage / "global-plan.json")
    if global_plan.get("overview_digest") != plan["overview_digest"]:
        raise SynthesisError("global plan does not match synthesis plan")
    claims = _all_claims(root, plan)
    manifest_before = read_json(paths.manifest, required=False)
    candidate = paths.stage / "candidate-output"
    if candidate.exists():
        shutil.rmtree(candidate)
    if paths.output.is_dir():
        shutil.copytree(paths.output, candidate)
    else:
        candidate.mkdir(parents=True)

    expected_topics = set(plan["topics"])
    for directory, suffix in ((candidate / "topics", ".md"), (candidate / "claims", ".json")):
        directory.mkdir(parents=True, exist_ok=True)
        for stale in directory.glob(f"*{suffix}"):
            if stale.stem not in expected_topics:
                stale.unlink()

    for topic_id in plan["dirty_topics"]:
        topic = plan["topics"][topic_id]
        markdown = render_topic(topic, claims[topic_id], plan["content_date"], plan["overview_commit"])
        atomic_write(candidate / "topics" / f"{topic_id}.md", markdown)
        atomic_write(candidate / "claims" / f"{topic_id}.json", canonical_json(claims[topic_id]))
    for topic_id in expected_topics - set(plan["dirty_topics"]):
        if not (candidate / "topics" / f"{topic_id}.md").is_file() or not (
            candidate / "claims" / f"{topic_id}.json"
        ).is_file():
            raise SynthesisError(f"Clean topic {topic_id} has no previous generated artifact")

    global_compacted = bool(global_plan.get("global_due"))
    previous_global = manifest_before.get("global", {}) if isinstance(manifest_before.get("global", {}), dict) else {}
    if global_compacted:
        global_payload = _validate_global(root, plan, global_plan)
        current = render_current(plan, claims, global_payload)
        max_chars = load_config(root)["global_compaction"]["max_chars"]
        if len(current) > max_chars:
            raise SynthesisError(f"Compact Current Synthesis exceeds max_chars={max_chars}")
        atomic_write(candidate / "current.md", current)
        global_state = {
            "candidate_digest": global_plan["candidate_digest"],
            "output_digest": digest_text(current),
            "overview_digest": plan["overview_digest"],
            "overview_commit": plan["overview_commit"],
            "content_date": plan["content_date"],
            "corpus": plan["corpus"],
            "compacted_at": parse_now(now).isoformat().replace("+00:00", "Z"),
            "pending_ingests": 0,
            "pending_topics": [],
        }
    else:
        current_path = candidate / "current.md"
        if not current_path.exists():
            raise SynthesisError("No previous current.md exists and global compaction was not due")
        pending_topics = sorted(set(previous_global.get("pending_topics", [])) | set(plan["dirty_topics"]))
        global_state = {
            **previous_global,
            "pending_ingests": global_plan["pending_ingests"],
            "pending_topics": pending_topics,
        }

    ledger = {
        "schema_version": 1,
        "overview_digest": plan["overview_digest"],
        "overview_commit": plan["overview_commit"],
        "paragraphs": plan["paragraphs"],
        "coverage": plan["coverage"],
    }
    atomic_write(candidate / "paragraph-ledger.json", canonical_json(ledger))
    topic_state = {
        topic_id: {
            "title": topic["title"],
            "input_digest": topic["input_digest"],
            "output_digest": digest_text((candidate / "topics" / f"{topic_id}.md").read_text(encoding="utf-8")),
            "claim_digest": digest_value(claims[topic_id]),
        }
        for topic_id, topic in plan["topics"].items()
    }
    manifest = {
        "schema_version": 1,
        "generated": True,
        "overview_digest": plan["overview_digest"],
        "overview_commit": plan["overview_commit"],
        "content_date": plan["content_date"],
        "corpus": plan["corpus"],
        "paragraph_count": plan["coverage"]["paragraph_count"],
        "topics": topic_state,
        "global": global_state,
    }
    atomic_write(candidate / "manifest.json", canonical_json(manifest))
    validate_output(root, plan, candidate)

    for subdir, suffix in (("topics", ".md"), ("claims", ".json")):
        destination = paths.output / subdir
        destination.mkdir(parents=True, exist_ok=True)
        for stale in destination.glob(f"*{suffix}"):
            if stale.stem not in expected_topics:
                stale.unlink()
        for topic_id in sorted(expected_topics):
            atomic_write(
                destination / f"{topic_id}{suffix}",
                (candidate / subdir / f"{topic_id}{suffix}").read_text(encoding="utf-8"),
            )
    atomic_write(
        paths.output / "current.md",
        (candidate / "current.md").read_text(encoding="utf-8"),
    )
    atomic_write(
        paths.output / "paragraph-ledger.json",
        (candidate / "paragraph-ledger.json").read_text(encoding="utf-8"),
    )
    atomic_write(paths.manifest, canonical_json(manifest))  # publication commit point: always last
    return {"global_compacted": global_compacted, "dirty_topics": plan["dirty_topics"]}


def validate_output(root: Path, plan: dict[str, Any], output: Path) -> dict[str, Any]:
    config = load_config(root)
    manifest = read_json(output / "manifest.json")
    ledger = read_json(output / "paragraph-ledger.json")
    if manifest.get("overview_digest") != ledger.get("overview_digest"):
        raise SynthesisError("Manifest and paragraph ledger overview digests differ")
    if manifest.get("overview_digest") != plan["overview_digest"]:
        raise SynthesisError("Generated synthesis is stale relative to automatic overview.md")
    paragraphs = ledger.get("paragraphs")
    coverage = ledger.get("coverage", {})
    if not isinstance(paragraphs, list) or coverage.get("paragraph_count") != len(paragraphs):
        raise SynthesisError("Paragraph ledger coverage count is invalid")
    if paragraphs != plan["paragraphs"] or coverage != plan["coverage"]:
        raise SynthesisError("Paragraph ledger differs from the deterministic synthesis plan")
    ids = {paragraph.get("id") for paragraph in paragraphs if isinstance(paragraph, dict)}
    if ids != set(coverage.get("assigned_paragraph_ids", [])) or len(ids) != len(paragraphs):
        raise SynthesisError("Paragraph ledger does not have fail-closed 100% assignment coverage")

    configured = set(topic_map(config))
    active_topics = set(plan["topics"])
    states = manifest.get("topics")
    if not active_topics <= configured or not isinstance(states, dict) or set(states) != active_topics:
        raise SynthesisError("Manifest topics do not exactly match the active controlled topics")
    topic_files = {path.stem for path in (output / "topics").glob("*.md")}
    claims_files = {path.stem for path in (output / "claims").glob("*.json")}
    if topic_files != active_topics or claims_files != active_topics:
        raise SynthesisError("Generated topic and claims files do not exactly match the active topics")
    for topic_id, state in states.items():
        if not isinstance(state, dict) or state.get("input_digest") != plan["topics"][topic_id]["input_digest"]:
            raise SynthesisError(f"Generated topic {topic_id} input digest differs from plan")
        topic_file = output / "topics" / f"{topic_id}.md"
        claims_file = output / "claims" / f"{topic_id}.json"
        if not topic_file.is_file() or not claims_file.is_file():
            raise SynthesisError(f"Generated topic {topic_id} is incomplete")
        if digest_text(topic_file.read_text(encoding="utf-8")) != state.get("output_digest"):
            raise SynthesisError(f"Generated topic {topic_id} output digest differs from manifest")
        claim_payload = load_topic_claims(root, topic_id, plan, source=claims_file)
        if digest_value(claim_payload) != state.get("claim_digest"):
            raise SynthesisError(f"Generated topic {topic_id} claims digest differs from manifest")

    current_path = output / "current.md"
    current = current_path.read_text(encoding="utf-8")
    if not current.startswith(GENERATED_NOTICE) or "## Executive Summary" not in current or "## Synthesis by Domain" not in current:
        raise SynthesisError("Generated compact synthesis is missing required structure")
    if "## Update History" in current or "## Open Questions" in current:
        raise SynthesisError("Generated compact synthesis embeds an independently published section")
    if len(generated_summary(current)) > GLOBAL_SUMMARY_MAX_CHARS:
        raise SynthesisError(
            f"Generated compact synthesis summary exceeds {GLOBAL_SUMMARY_MAX_CHARS} characters"
        )
    corpus = manifest.get("corpus")
    if corpus != plan["corpus"]:
        raise SynthesisError("Generated synthesis corpus snapshot is stale")
    if manifest.get("paragraph_count") != plan["coverage"]["paragraph_count"]:
        raise SynthesisError("Generated synthesis paragraph count differs from plan")
    global_state = manifest.get("global", {})
    global_corpus = global_state.get("corpus") if isinstance(global_state, dict) else None
    for key in ("episode_count", "source_count"):
        value = global_corpus.get(key) if isinstance(global_corpus, dict) else None
        if not isinstance(value, int) or isinstance(value, bool) or value < 0:
            raise SynthesisError(f"Generated synthesis has invalid global {key}")
        if f"{key}: {value}\n" not in current:
            raise SynthesisError(f"Generated compact synthesis metadata differs for {key}")
    if f"as_of_overview_commit: {global_state.get('overview_commit', '')}\n" not in current:
        raise SynthesisError("Generated compact synthesis overview commit differs from global state")
    if f"last_updated: {global_state.get('content_date', '')}\n" not in current:
        raise SynthesisError("Generated compact synthesis content date differs from global state")
    if len(current) > config["global_compaction"]["max_chars"]:
        raise SynthesisError("Generated compact synthesis exceeds its configured maximum size")
    known = known_wiki_keys(root)
    broken = sorted(set(WIKILINK_RE.findall(current)) - known)
    if broken:
        raise SynthesisError(f"Generated compact synthesis has broken wikilinks: {broken[:10]}")
    expected_digest = global_state.get("output_digest") if isinstance(global_state, dict) else None
    if expected_digest != digest_text(current):
        raise SynthesisError("Generated compact synthesis digest differs from manifest")
    return {
        "paragraph_count": len(paragraphs),
        "topic_count": len(states),
        "current_chars": len(current),
    }


def validate_repository(root: Path) -> dict[str, Any]:
    return validate_output(root, build_plan(root), Paths(root).output)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("plan", "prepare-global", "render", "validate"))
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--now")
    parser.add_argument("--force-global", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.command == "plan":
            result = plan_repository(args.root, now=args.now, force_global=args.force_global)
        elif args.command == "prepare-global":
            result = prepare_global(args.root, now=args.now)
        elif args.command == "render":
            result = render_repository(args.root, now=args.now)
        else:
            result = validate_repository(args.root)
    except (OSError, SynthesisError) as error:
        print(f"Synthesis error: {error}", file=sys.stderr)
        return 1
    print(canonical_json(result), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
